config-ver: '1.2' # Do not change this 

# Hi, welcome to the LoginTo premium configuration, you will need to write here only a few information and follow the comments 
  
# if your network will support bedrock players use a prefix that java names cannot contain, for example a dot (.) , but NOT use the underscore (_), letters, numbers or anything affected by SQL case sensitivity 
  
# Should LoginTo authenticate players with mojang? (if this option is false the proxy will be 100% offline, if true the classic authentication will be executed) 
loginto-premium-auth: 'true' 
  

# This will be the database info for sharing data with the bukkit server 
database: 
  
  # This is the type of database that will be used by the plugins for comunicating
  # Note: use h2 if you can't use a mysql database or if you have a single machine running the network. But if you can use mysql, it's racomanded to do it
  # Options:
  # mysql -> For MySQL (ONLY CONNECTION, you will need an external mysql database for this option)
  # h2 -> For H2 database
  database-type: 'h2'

  # Database information, if you are using h2, change just the port if it's not 9092
  database:
    # The host for the database, if this param is null, the host will be 'localhost'
    host: ""

    # The port of your database, the H2 default port is 9092, while the default mysql port is 3306
    port: 9092 

    # The password for your mysql database
    user: ""

    # The password for your mysql database
    password: ""

    # The name of the mysql database, by default this will be "LoginTo_Sharing"
    name: ""
  
  
# This is the user authentication variables 
# They will be used to validate an username and bedrock players 
user-auth: 
  
    # This will be the prefix for bedrock players 
    # WARN: The bedrock feature is nothing special, basicalle while validating the username we will check if the name start with the prefix 
    # Also as the warn on top, do not use java-accepted characters or sql sensitive characters 
    bedrock-prefix: '.' 
  
# This will be the section for the proxy messages 
# Some messages are client only, so you can't change that 
messages: 
  
    # This message will appear if the player joining has an invalid username 
    invalid-username: 'You got kicked because you username is invalid: %username%' 
  
anti_join-spam: 
    # This is for blocking the connection that will join and leave in a short period of time 
    anti_join-spam: 'true' 
  
    # This is the cooldown in seconds, if a player enter the network too many times in this period, it will be kicked 
    # By default this is set to 15, witch is pretty low, this is because an ip is a personal information,    # and it can't be saved for a long time without permission, if you are creating a large network, set this to 30-50 
    cooldown: '15' 
  
    # This is how many times the player can connect/reconnect before getting kicked, the sweet spot for this setting is 3-6, or if you want you can set to 1/2 and the cooldown to 5/10  
    max-connection: '3' 

    # This will be the timeout (in seconds) of the player ban when it joins too many times 
    ban-time: 300 
  
    # The message that the player will see if he will join too many times 
    ban-message: 'You joined too many times with this ip, wait a few minutes' 