ConfigVersion: "1.8" # DO NOT CHANGE THIS
# -------------------------------------------------------------------------------------------------- #
#                                                                                                    #
#                                       LoginTo Configuration                                        #
#                                                                                                    #
# -------------------------------------------------------------------------------------------------- #


auth-security:

  # Kick the player if they provide an incorrect password during /login?
  kick-on-invalid-password: true
  # Maximum login attempts before getting kicked
  max-login-attempts: 3

  # Kick players who stay unauthenticated for too long?
  kick-on-auth-timeout: true
  # Seconds allowed to authenticate before the kick occurs
  auth-timeout-seconds: 10

password-requirements:
  # Require specific special characters in the password during registration?
  require-special-chars: false
  # List the characters required if the setting above is true
  required-char-list: ''

  # Define password length constraints
  length-check:
    enabled: true
    min-length: 8
    max-length: 32


# World and teleportation
spawn-settings:
  # Enable automatic teleportation to a specific location on join?
  teleport-on-join: false
  
  # Target dimension for the teleport (e.g., world, world_nether, world_the_end)
  target-dimension: 'world'
  
  # Exact coordinates for the teleportation point
  spawn-coordinates:
    x: 0
    y: -64
    z: 0
    
  # Return the player to their last known location after a successful login?
  restore-previous-location: true


# Integrations and webhooks
integrations:

  proxy:
    # Specify the server where players should be sent after logging into your network (e.g., 'lobby-1'). 
    # If you are not using a proxy or wish to disable this feature, leave this field empty.
    server-post-login: ""

  discord:
    # Webhook URLs and custom messages (Supports Discord Markdown & PAPI)
    # Variables: %playerName%, %targetPlayer%
    
    register-webhook-url: ''
    register-message: "**%playerName%** completed the registration"

    login-webhook-url: ''
    login-message: "**%playerName%** completed the login"
    
    delete-account-webhook-url: ''
    delete-account-message: "**%playerName%** deleted **%targetPlayer%**'s account"

    password-change-webhook-url: ''
    password-change-message: "**%playerName%** changed his password"


# Storage
storage:

  # Storage Methods: sqlite, mysql, postgre, h2
  # Changing this requires a full server reboot
  storage-type: "sqlite"

  database:
    # Connection details for the database (for sqlite or h2, you will need to change only the name)
    host: "localhost"
    port: 3306
    name: "LoginTo_DB"
    user: ""
    password: ""


# Premium system
premium:
  # Enables AutoLogin, /premium, /cracked commands and make unusable the proxy command unless the user is logged.
  # Requires a Proxy (Velocity/Bungee) with the plugin installed, and if you are running the proxy and the server on 
   # two different machines or you are running in a dedicated host that uses pderodactyl, use mysql
  enable-premium-features: false

  storage:
    # Database type for cross-server communication (mysql or h2), it's raccomanded mysql if you can
    database-type: "h2"

    database:
      host: "localhost"
      # If the port is 0, it will be the database's default port (3306 for mysql and 9092 for h2)
      port: 0
      user: "sa"
      password: ""
      # Only used for MySQL; H2 defaults to 'LoginTo_Sharing'
      database-name: "LoginTo_Sharing"

logging:
  # This feature is for logging all the players that joins in the server
  logging: true

  # The time format for showing the current date
  # Do not use the space " " for the time, you can do this "hh-mm-ss dd-MM-yyyy", but not "hh mm ss dd MM yyyy", if you want, tell your staff to use only /getlogs <user> without the day
  # You can change the time (ss:mm:hh) and not using the space, but if you use the /getlogs command with the time selector, the date must remain "dd/MM/yyyy"
  date-format: "HH:mm:ss dd/MM/yyyy"



plugin-utility:
  # Check for new updates on startup and notify the console?
  enable-update-checker: true
  
  # Show the 'Service offered by LoginTo' watermark?, if you want to support me, consider leaving this on
  show-watermark: true




  