name: LoginTo
version: '1.7-release'
main: org.LoginTo
api-version: '1.21'
load: STARTUP
authors: [ Yager400 ]
description: A simple plugin that add a register, login, delacc and premium
website: https://modrinth.com/plugin/loginto
commands:
  register:
  login:
  delacc:
  premium:
  changepassword:
  loginto-reload:
permissions:
  loginto.register:
    default: true
  loginto.login:
    default: true
  loginto.delacc:
    default: op
  loginto.premium:
    default: true
  loginto.changepassword:
    default: true
  loginto.reload:
    default: op
