name: LoginTo
version: '3.3'
main: net.loginto.bukkit.LoginTo
api-version: '1.16.5'
api: spigot
authors: [ Yager400 ]
softdepend: [PlaceholderAPI, PacketEvents]
commands:
  register:
    usage: /register <password> <confirm_password>
    aliases: [r, reg]
  login:
    usage: /login <password>
    aliases: [l]
  delacc:
    usage: /delacc <user> <confirm>
  changepassword:
    usage: /changepassword <old_password> <new_password>
  premium:
    usage: /premium [optional]<user>
  cracked:
    usage: /cracked
  getlogs:
    usage: "/getlogs <user> [optional]<dd/MM/yyyy>"
permissions:
  loginto.register:
    default: true
  loginto.login:
    default: true
  loginto.delacc:
    default: op
  loginto.changepassword:
    default: true
  loginto.premium.me:
    default: true
  loginto.premium.other:
    default: op
  loginto.cracked.me:
    default: true
  loginto.getlogs:
    default: op
