name: LoginTo
version: 3.5.1
main: net.loginto.bukkit.LoginTo
api-version: 1.16
api: spigot
authors: [ Yager400 ]
softdepend: [ PlaceholderAPI, PacketEvents ]
commands:
  register:
    usage: /register <password> <confirm_password>
    aliases: [ "r" ]
  login:
    usage: /login <password>
    aliases: [ "l" ]
  unregister:
    usage: /unregister <user> <confirm>
    aliases: [ "delacc" ]
  changepassword:
    usage: /changepassword <new_password> <otp_code>
  premium:
    usage: /premium [optional]<user>
  cracked:
    usage: /cracked
  getlogs:
    usage: /getlogs <user> [optional]<dd/MM/yyyy>
  otp:
    usage: /otp
permissions:
  loginto.register:
    default: true
  loginto.login:
    default: true
  loginto.delacc:
    default: op
  loginto.changepassword:
    default: true
  loginto.premium.me:
    default: true
  loginto.premium.other:
    default: op
  loginto.cracked.me:
    default: true
  loginto.getlogs:
    default: op
  loginto.otp:
    default: true
